name: mawl

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Make Another Weblog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build & deploy to GitHub Pages
        uses: phillmv/mawl@main